version: '3'
services:
  postgres:
    image: docker.io/library/postgres:alpine
    networks:
      - goals-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: goals
      POSTGRES_USER: goals
      POSTGRES_PASSWORD: goals
    ports:
      - "5432:5432"
    expose:
      - 5432
      
  goals-api:
    build: .
    networks:
      - goals-net
    environment:
      - DB_JDBC_URI=jdbc:postgresql://postgres:5432/goals?user=goals&password=goals
    depends_on:
      - postgres
    restart:
      always
    ports:
      - "8080:8080"
      

    
networks:
  goals-net:

volumes:
  pgdata: