version: '3'
services:
  postgres:
    image: docker.io/library/postgres:alpine
    # networks:
    #   - goals-net
    environment:
      POSTGRES_DB: goals
      POSTGRES_USER: goals
      POSTGRES_PASSWORD: goals
    ports:
      - "5432:5432"